### ISSUE TITLE
Common, error

### ISSUE THREAD

**Issue by dtolnay** [eupn/macrotest#11]
What is this stuff? Are users supposed to use it? It wasn't clear from the docs what role they play, since the examples only use TestCases.

<img src="https://user-images.githubusercontent.com/1940490/67790134-78974880-fa32-11e9-9d24-e08fad6d4313.png" width="50%">

<img src="https://user-images.githubusercontent.com/1940490/67790137-7b923900-fa32-11e9-8804-bd804f88690a.png" width="50%">

**Comment by eupn** [comment]
Error is the `macrotest`'s error type, it's used mostly internally and doesn't show up in external API. Although it should be hidden behind `pub(crate)` visibility. 

`common`'s types are no longer used and should be removed, thank you for reminding me about them!

**Comment by eupn** [comment]
Closed via #19.
