### ISSUE TITLE
Consider normalizing the expanded code

### ISSUE THREAD

**Issue by dtolnay** [eupn/macrotest#14]
https://github.com/eupn/macrotest/blob/0beeb43bb059ac58c33f84b889c53a401fbed0a6/test-procmacro-project/tests/expand/attribute.expanded.rs#L1-L6

I think the above lines should be stripped from the expanded code prior to comparing it against expanded.rs.

That way any time rustc makes insignificant changes to this header, we only need one patch in macrotest to accommodate the new header rather than updating every expanded.rs in every project downstream.

**Comment by eupn** [comment]
That's reasonable. I see this prelude every time and it seems to be only an unrelated technical detail.

**Comment by eupn** [comment]
Closed via #20.
