### ISSUE TITLE
Print notice when updating .expanded.rs files

### ISSUE THREAD

**Issue by dtolnay** [eupn/macrotest#30]
Currently a `cargo test` with deleted .expanded.rs files will silently pass with no indication that new files have been written. It would be better to print some sort of notice, since the tests didn't actually test anything; a human would need to look at the new files to confirm that they are as intended.

**Comment by eupn** [comment]
We can print a notice via stderr; IIRC it's not filtered by cargo even when tests are passed.

**Comment by dtolnay** [comment]
Right, writing directly to stderr is not filtered.

```rust
let _ = writeln!(std::io::stderr(), "...");
```

**Comment by dtolnay** [comment]
This still doesn't work. You need to write the message directly to io::stderr(), not using eprintln.

**Comment by eupn** [comment]
Wow, that's unexpected!
