### ISSUE TITLE
Wrong diff

### ISSUE THREAD

**Issue by dtolnay** [eupn/macrotest#31]
To test what a test failure looks like, I tried this simple test case:

```rust
fn main() {
    println!();
}
```

and an .expanded.rs file with an extra newline at the top to trigger a mismatch:

```rust
​
fn main() {
    ::std::io::_print(::core::fmt::Arguments::new_v1(
        &["\n"],
        &match () {
            () => [],
        },
    ));
}
```

The diff printed by `macrotest` is:

```console
Running 1 macro expansion tests
x - different!
Diff [lines: 5 added, 0 removed]:
--------------------------
+#![feature(prelude_import)]
+#[prelude_import]
+use std::prelude::v1::*;
+#[macro_use]
+extern crate std;
 fn main() {
     ::std::io::_print(::core::fmt::Arguments::new_v1(
         &["\n"],
         &match () {
             () => [],
         },
     ));
 }
--------------------------
```

It claims 5 added/0 removed. The correct diff would have 0 added/1 removed.

**Comment by eupn** [comment]
Probably related to https://github.com/johannhof/difference.rs/issues/28. I'll try a different (no pun intended) library.

**Comment by dtolnay** [comment]
Part of it is that, but part of it is the filtered lines at the top should not be in what we hand to the diff library.
