### ISSUE TITLE
Configurable refresh

### ISSUE THREAD

**Issue by Emoun** [eupn/macrotest#41]
I would be useful if we were able to configure whether the "refresh" outcome of `expand` could be turned off or result in a failure. 

I specifically have a setup where I'd rather have a missing `.expanded.rs` file trigger a test failure and not create the expanded file for me. I like that the file could be created for me, but I'd prefer if it was only when I specifically ask for it.

A possible solution is simply adding another method that doesn't create expanded files when they are missing, simply failing instead:

```Rust
#[test]
pub fn pass() {
    macrotest::expand_without_refresh("tests/expand/*.rs");
}
```

**Comment by eupn** [comment]
@Emoun 

Sure, it seems straightforward to implement.

**Comment by Emoun** [comment]
@eupn Thanks for the quick  response and implementation. It seems to work as expected for me.
Much appreciated.

**Comment by eupn** [comment]
@Emoun sure, thank you for the feedback!
