### ISSUE TITLE
Allow the passing of flags to expand

### ISSUE THREAD

**Issue by Emoun** [eupn/macrotest#43]
I would like the possibility of passing flags to cargo in  `macrotest::expand_without_refresh`.

My use case is that I would like to test my expansion with different crate features. It seems to me that `macrotest::expand_without_refresh` simply calls `cargo expand`, which means the default features of the crate under test are used.
I would like to be able to disable the default features and enable other features in a granular fashion:

```
// Test expansion without any features
macrotest::expand_without_refresh("some_test_file.rs", "--no-default-features"); 

// Test expansion with only feature "some_feature" enabled
macrotest::expand_without_refresh("some_test_file.rs", "--features some_feature"); 
```

Of course the exact API doesn't have to look like the above.

**Comment by eupn** [comment]
@Emoun this feature is implemented in #46. Feel free to pull this branch and test the new API against your requirements.

Example from tests that enables `test-feature` during macro expansion:

```rust
#[test]
pub fn pass_args() {
    macrotest::expand_args("tests/expand_args/*.rs", &["--features", "test-feature"]);
}

#[test]
pub fn pass_expect_expanded_args() {
    // If you delete one of the `.expanded.rs` files, this test will fail.
    macrotest::expand_args("tests/expand_args/*.rs", &["--features", "test-feature"]);
}

#[test]
#[should_panic]
pub fn fail_expect_expanded_args() {
    // This directory doesn't have expanded files but since they're expected, the test will fail.
    macrotest::expand_without_refresh_args("tests/no_expanded_args/*.rs", &["--features", "test-feature"]);
}
```

**Comment by Emoun** [comment]
@eupn I have tested the branch and it seems to work as I expected. Note that I have only tested `macrotest::expand_without_refresh_args`, as that is the only one I can make use of.

I look forward to seeing this in a future release.

**Comment by eupn** [comment]
@Emoun good! Will release a new version ASAP.
