### ISSUE TITLE
Bug: Running multiple expansion tests may interfere with each other

### ISSUE THREAD

**Issue by Emoun** [eupn/macrotest#44]
Using `macrotest::expand_without_refresh` in multiple tests may cause them to interfere with each other destructively.

Say we have 2 expansion tests we want to run: `set_1.rs` and `set_2.rs` with each their `.expanded.rs` file to test against.
We then want to run these expansion tests in different tests:
```rust
#[test]
fn test_set_1(){
	macrotest::expand_without_refresh("tests/expand/set_1.rs");
}
	
#[test]
fn test_set_2(){
	macrotest::expand_without_refresh("tests/expand/set_2.rs");
}
```
When we run this with `cargo test` we get the following error:
```
---- test_set_1 stdout ----
Running 1 macro expansion tests
Expansion error:
error: no bin target named `set_1`
        Did you mean `set_2`?
```
However if we run these test one at a time with `cargo test -- --test-threads=1` we do not get this error.
I have create [a repository](https://github.com/Emoun/macrotest_race_condition) that exhibits this behavior.
Note that this is regardless of the contents of the files under test. In this example the `set_2.rs` test should actually fail because the `expanded.rs` file is not correct. But even if we change this, the above message will still be thrown.

I realize that we could run these two file in one test (`macrotest::expand_without_refresh("tests/expand/*.rs");`), however, my original use case requires me to have expansion tests split because of different features I want to test.

Also, I have no idea whether this is a problem with `macrotest` itself or with `cargo expand`.

**Comment by eupn** [comment]
@Emoun 

Hello and thank you for this report!

The `macrotest` crate is most likely the reason because it creates a temporary cargo crate for each "set" of expansion tests and those crates (or their names/paths) are happened to be non-unique thus causing the interference. One possible solution to this might be to create temporary crates with randomized name&path to make them unique for each "set" of expansion tests thus eliminating the interference.

**Comment by Emoun** [comment]
@eupn thanks for the clarification, I was quite confused about what `no bin target` referred to.

If you would like me to help you test a potential fix you implement just @ me and I'll try to run it on my use case.

**Comment by eupn** [comment]
@Emoun feel free to pull this branch (via git dependency in cargo) and run against your project: https://github.com/eupn/macrotest/pull/45.

As soon as this PR gets merged I publish a new version (`v1.0.3`) on crates.io.

**Comment by Emoun** [comment]
@eupn Yep, can confirm #45 fixes this bug.

Thanks for the quick response to this issue and the quick fix.

**Comment by eupn** [comment]
@Emoun a new version `1.0.3` was published on crates.io.
