### ISSUE TITLE
Request: MSRV

### ISSUE THREAD

**Issue by Emoun** [eupn/macrotest#52]
I would like request that `macrotest` decides on a Minimum Supported Rust Version (MSRV).

The latest release `1.0.6` doesn't build on Rust v1.34.
This is a problem for [`duplicate`](https://github.com//emoun/duplicate), as we have an MSRV of 1.34. Therefore, it cannot update to the latest version: see [this build result](https://github.com/Emoun/duplicate/runs/1504266340?check_suite_focus=true).
As long as `macrotest` doesn't commit to an MSRV (that is compatible with `duplicate`'s), I must assume each release (even patch releases) may break our setup.

Of course, I would prefer that the eventual MSRV chosen for `macrotest` be compatible with `duplicate`'s MSRV.
It can be found on [crates.io](https://crates.io/crates/duplicate) in the "MSRV Policy" section.
You can also see how I decided on an MSRV policy on [this issue](https://github.com/Emoun/duplicate/issues/18).
You can also look at the Github Actions and Travis CI setups for how `duplicate` enforces the MSRV.

Even if `macrotest` doesn't get and MSRV of 1.34, I would prefer to know what the policy is. I can then use that knowledge to guide any MSRV policy updates.

**Comment by eupn** [comment]
Hello @Emoun and sorry for making your code break. I'll definitely make sure that this crate has MSRV and it seems that it could work with 1.34 (thanks to #53).

**Comment by eupn** [comment]
The `v1.0.7` version should support 1.34.0 and higher. Please feel free to reopen this issue if this is not the case, now or in the future.
