### ISSUE TITLE
Use the same edition as the crate under test

### ISSUE THREAD

**Issue by eupn** [eupn/macrotest#7]
Copy the `edition` field of `package` section of the crate's Cargo.toml into the "temporary crate"'s manifest. It should be reasonable to assume that the test cases are using the same edition as the crate which macros they're testing.

**Comment by dtolnay** [comment]
> It should be reasonable to assume that the test cases are using the same edition as the crate which macros they're testing.

I agree this would be reasonable.

Alternatively I would also be fine supporting 2018 edition only.
