### ISSUE TITLE
Parallel tests fail in workspace project

### ISSUE THREAD

**Issue by taqtiqa-mark** [eupn/macrotest#71]
Thank you for the effort you have put into making macrotest, and for making it open source.

I ran into this issue in the course of trying to isolate what appears to be unexpected behavior.  

PR #72 proposes to add a workspace project example, and this error can be observed by checking out the first commit in the PR.

```bash
cd workspace-project
cargo test -- --nocapture
```

Should show these two results for `parallel_1` and `parallel_2` test cases:

```bash
tests/expand/second.rs - different!
Diff [lines: 6 added, 1 removed]:
--------------------------
 #[macro_use]
 extern crate test_project;
 pub fn main() {
+    {
+        let mut temp_vec = Vec::new();
+        temp_vec.push(1);
+        temp_vec
+    };
-    ();
 }
+
--------------------------



thread 'parallel_2' panicked at '1 of 1 tests failed', /home/user/src/macrotest/src/expand.rs:171:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test parallel_2 ... FAILED
tests/expand/first.rs - different!
Diff [lines: 2 added, 1 removed]:
--------------------------
 #[macro_use]
 extern crate test_project;
 pub fn main() {
+    Vec::new();
-    ();
 }
+
--------------------------



thread 'parallel_1' panicked at '1 of 1 tests failed', /home/user/src/macrotest/src/expand.rs:171:9
test parallel_1 ... FAILED

failures:

failures:
    parallel_1
    parallel_2

```

**Comment by taqtiqa-mark** [comment]
Workaround:

```bash
cargo test -- --test-threads=1
```

**Comment by ijackson** [comment]
This may be tangentially related to #83/#84.  I don't think #84 will fix it but perhaps better choice of subdirectory name would.

**Comment by taiki-e** [comment]
> ```shell
> tests/expand/second.rs - different!
> Diff [lines: 6 added, 1 removed]:
> --------------------------
>  #[macro_use]
>  extern crate test_project;
>  pub fn main() {
> +    {
> +        let mut temp_vec = Vec::new();
> +        temp_vec.push(1);
> +        temp_vec
> +    };
> -    ();
>  }
> +
> --------------------------
> ```

This is due to the crate that defining macro is "wrkspc-test" but you are importing `extern crate test_project;`.
Changing `extern crate test_project;` to `extern crate wrkspc_test;` would give the correct result.

Closing as this doesn't seem to macrotest bug.
