### ISSUE TITLE
Support workspace inheritance

### ISSUE THREAD

**Issue by taqtiqa-mark** [eupn/macrotest#74]
I've encountered this issue while implementing a [infinyon/fluvio](https://www.infinyon.com/blog/2021/04/rust-custom-test-harness/) plugin-style integration test harness for Minitest, PR tikv/minitrace-rust/pull/127.  

I have now reproduced the issue in a `test-virtual` project that will, hopefully, land here via PR #72.

The `test-virtual` example shows how to setup macrotest with a generic (non-`libtest`) test harness, and allows macrotest users to compare this plugin-style integration test suite with the default Rust `libtest` test harness. 

At the moment the `test-virtual` project returns this error:

```bash
cargo test integration-tests 

<snip>

Expansion error:
error: Package `wrkspc-test-tests v0.0.0 (/home/user/src/macrotest/test-virtual/target/tests/wrkspc-test/macrotest000)` does not have the feature `test-feature`
```

I've banged my head on both projects but can't seem to figure out where the mismatch is occuring.

Appreciate any help or insights you can share.

**Comment by taqtiqa-mark** [comment]
Note to self to investigate possible workaround:

Cargo virtual manifests do not support the `[features]` stanza (without also
having the `[package]` stanza).  See [Cargo issue 4942](https://github.com/rust-lang/cargo/issues/4942).

**Comment by taiki-e** [comment]
This is because workspace inheritance is not yet supported.

**Comment by taiki-e** [comment]
> ```shell
> error: Package `wrkspc-test-tests v0.0.0 (/home/user/src/macrotest/test-virtual/target/tests/wrkspc-test/macrotest000)` does not have the feature `test-feature`
> ```

Ah, nah, the direct reason for this error itself could be due to a failure to parse the edition (fixed by https://github.com/eupn/macrotest/pull/92).

However, as far as I can see #72, even if that error was corrected, it is likely that another error was shown because of the workspace inheritance.
